### ISSUE TITLE
Change comment textarea to use placeholder instead of default value.

### ISSUE THREAD

**Issue by wennyyustalim** [haveaqiupill/software-product-sprint#7]
https://github.com/haveaqiupill/software-product-sprint/blob/262eff88d2d59070ae11c22c56b49bac34c19ca2/portfolio/src/main/webapp/pages/blog.html#L45

Sorry I missed this one in previous review. Should we use placeholder instead of default value? So when I click on the comment box I won't need to erase the default comment before writing mine.

Something like:
```
<textarea name="comment-input" placeholder="Enter some random comment here..."></textarea>
```

**Comment by haveaqiupill** [comment]
okay!
